// AUTOGENERATED: 5cf7089ba9a6daecfa08d99b989d03f8
// AUTOGENERATED: 09.01.2012 13:05:47
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.services;

import de.kalass.sonoscontrol.api.core.EventListener;
import javax.annotation.CheckForNull;

import de.kalass.sonoscontrol.api.core.Callback0;
import de.kalass.sonoscontrol.api.core.Callback1;
import de.kalass.sonoscontrol.api.model.audioin.TransportSettings;
import de.kalass.sonoscontrol.api.model.audioin.GetAudioInputAttributesResult;
import de.kalass.sonoscontrol.api.model.audioin.GetLineInLevelResult;
import de.kalass.sonoscontrol.api.model.audioin.RightLineInLevel;
import de.kalass.sonoscontrol.api.model.audioin.LeftLineInLevel;
import de.kalass.sonoscontrol.api.model.MemberID;
import de.kalass.sonoscontrol.api.model.audioin.AudioInputName;
import de.kalass.sonoscontrol.api.model.audioin.ObjectID;
import de.kalass.sonoscontrol.api.model.audioin.LineInConnected;
import de.kalass.sonoscontrol.api.model.audioin.Playing;
import de.kalass.sonoscontrol.api.model.audioin.Icon;

public interface AudioInService {


    @CheckForNull
    RightLineInLevel getLastValueForRightLineInLevel();

    void addRightLineInLevelListener(EventListener<RightLineInLevel> listener);

    void removeRightLineInLevelListener(EventListener<RightLineInLevel> listener);

    @CheckForNull
    LeftLineInLevel getLastValueForLeftLineInLevel();

    void addLeftLineInLevelListener(EventListener<LeftLineInLevel> listener);

    void removeLeftLineInLevelListener(EventListener<LeftLineInLevel> listener);

    @CheckForNull
    AudioInputName getLastValueForAudioInputName();

    void addAudioInputNameListener(EventListener<AudioInputName> listener);

    void removeAudioInputNameListener(EventListener<AudioInputName> listener);

    @CheckForNull
    LineInConnected getLastValueForLineInConnected();

    void addLineInConnectedListener(EventListener<LineInConnected> listener);

    void removeLineInConnectedListener(EventListener<LineInConnected> listener);

    @CheckForNull
    Playing getLastValueForPlaying();

    void addPlayingListener(EventListener<Playing> listener);

    void removePlayingListener(EventListener<Playing> listener);

    @CheckForNull
    Icon getLastValueForIcon();

    void addIconListener(EventListener<Icon> listener);

    void removeIconListener(EventListener<Icon> listener);


    <C extends Callback1<TransportSettings>> C startTransmissionToGroup(MemberID coordinatorID, C callback);

    <C extends Callback0> C stopTransmissionToGroup(MemberID coordinatorID, C callback);

    <C extends Callback0> C setAudioInputAttributes(AudioInputName desiredName, Icon desiredIcon, C callback);

    <C extends Callback1<GetAudioInputAttributesResult>> C retrieveAudioInputAttributes(C callback);

    <C extends Callback0> C setLineInLevel(LeftLineInLevel desiredLeftLineInLevel, RightLineInLevel desiredRightLineInLevel, C callback);

    <C extends Callback1<GetLineInLevelResult>> C retrieveLineInLevel(C callback);

    <C extends Callback0> C selectAudio(ObjectID objectID, C callback);

}
