// AUTOGENERATED: fdc3fee34d22382d0d6708339bef4b78
// AUTOGENERATED: 09.01.2012 13:05:47
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.services;

import de.kalass.sonoscontrol.api.core.EventListener;
import javax.annotation.CheckForNull;

import de.kalass.sonoscontrol.api.core.Callback0;
import de.kalass.sonoscontrol.api.core.Callback1;
import de.kalass.sonoscontrol.api.model.deviceproperties.LEDState;
import de.kalass.sonoscontrol.api.model.deviceproperties.Invisible;
import de.kalass.sonoscontrol.api.model.deviceproperties.GetZoneAttributesResult;
import de.kalass.sonoscontrol.api.model.deviceproperties.HouseholdID;
import de.kalass.sonoscontrol.api.model.deviceproperties.GetZoneInfoResult;
import de.kalass.sonoscontrol.api.model.deviceproperties.AutoplayIncludeLinkedZones;
import de.kalass.sonoscontrol.api.model.deviceproperties.AutoplayRoomUUID;
import de.kalass.sonoscontrol.api.model.deviceproperties.AutoplayVolume;
import de.kalass.sonoscontrol.api.model.deviceproperties.SpeakerSize;
import de.kalass.sonoscontrol.api.model.deviceproperties.AutoplayUseVolume;
import de.kalass.sonoscontrol.api.model.deviceproperties.SettingsReplicationState;
import de.kalass.sonoscontrol.api.model.deviceproperties.ZoneName;
import de.kalass.sonoscontrol.api.model.deviceproperties.ExtraInfo;
import de.kalass.sonoscontrol.api.model.deviceproperties.ChannelMapSet;
import de.kalass.sonoscontrol.api.model.deviceproperties.DisplaySoftwareVersion;
import de.kalass.sonoscontrol.api.model.deviceproperties.MACAddress;
import de.kalass.sonoscontrol.api.model.deviceproperties.HardwareVersion;
import de.kalass.sonoscontrol.api.model.deviceproperties.SettingID;
import de.kalass.sonoscontrol.api.model.deviceproperties.SettingURI;
import de.kalass.sonoscontrol.api.model.deviceproperties.SerialNumber;
import de.kalass.sonoscontrol.api.model.deviceproperties.SoftwareVersion;
import de.kalass.sonoscontrol.api.model.deviceproperties.IPAddress;
import de.kalass.sonoscontrol.api.model.deviceproperties.IsZoneBridge;
import de.kalass.sonoscontrol.api.model.deviceproperties.CopyrightInfo;
import de.kalass.sonoscontrol.api.model.deviceproperties.Icon;

public interface DevicePropertiesService {


    @CheckForNull
    SettingsReplicationState getLastValueForSettingsReplicationState();

    void addSettingsReplicationStateListener(EventListener<SettingsReplicationState> listener);

    void removeSettingsReplicationStateListener(EventListener<SettingsReplicationState> listener);

    @CheckForNull
    ZoneName getLastValueForZoneName();

    void addZoneNameListener(EventListener<ZoneName> listener);

    void removeZoneNameListener(EventListener<ZoneName> listener);

    @CheckForNull
    ChannelMapSet getLastValueForChannelMapSet();

    void addChannelMapSetListener(EventListener<ChannelMapSet> listener);

    void removeChannelMapSetListener(EventListener<ChannelMapSet> listener);

    @CheckForNull
    Invisible getLastValueForInvisible();

    void addInvisibleListener(EventListener<Invisible> listener);

    void removeInvisibleListener(EventListener<Invisible> listener);

    @CheckForNull
    IsZoneBridge getLastValueForIsZoneBridge();

    void addIsZoneBridgeListener(EventListener<IsZoneBridge> listener);

    void removeIsZoneBridgeListener(EventListener<IsZoneBridge> listener);

    @CheckForNull
    Icon getLastValueForIcon();

    void addIconListener(EventListener<Icon> listener);

    void removeIconListener(EventListener<Icon> listener);


    <C extends Callback0> C setLEDState(LEDState desiredLEDState, C callback);

    <C extends Callback1<LEDState>> C retrieveLEDState(C callback);

    <C extends Callback0> C setInvisible(Invisible desiredInvisible, C callback);

    <C extends Callback1<Invisible>> C retrieveInvisible(C callback);

    <C extends Callback0> C addBondedZones(ChannelMapSet channelMapSet, C callback);

    <C extends Callback0> C removeBondedZones(ChannelMapSet channelMapSet, C callback);

    <C extends Callback0> C createStereoPair(ChannelMapSet channelMapSet, C callback);

    <C extends Callback0> C separateStereoPair(ChannelMapSet channelMapSet, C callback);

    <C extends Callback0> C setZoneAttributes(ZoneName desiredZoneName, Icon desiredIcon, C callback);

    <C extends Callback1<GetZoneAttributesResult>> C retrieveZoneAttributes(C callback);

    <C extends Callback1<HouseholdID>> C retrieveHouseholdID(C callback);

    <C extends Callback1<GetZoneInfoResult>> C retrieveZoneInfo(C callback);

    <C extends Callback0> C setAutoplayLinkedZones(AutoplayIncludeLinkedZones includeLinkedZones, C callback);

    <C extends Callback1<AutoplayIncludeLinkedZones>> C retrieveAutoplayLinkedZones(C callback);

    <C extends Callback0> C setAutoplayRoomUUID(AutoplayRoomUUID roomUUID, C callback);

    <C extends Callback1<AutoplayRoomUUID>> C retrieveAutoplayRoomUUID(C callback);

    <C extends Callback0> C setAutoplayVolume(AutoplayVolume volume, C callback);

    <C extends Callback1<AutoplayVolume>> C retrieveAutoplayVolume(C callback);

    <C extends Callback0> C importSetting(SettingID settingID, SettingURI settingURI, C callback);

    <C extends Callback0> C setSpeakerSize(SpeakerSize speakerSize, C callback);

    <C extends Callback1<SpeakerSize>> C retrieveSpeakerSize(C callback);

    <C extends Callback0> C setUseAutoplayVolume(AutoplayUseVolume useVolume, C callback);

    <C extends Callback1<AutoplayUseVolume>> C retrieveUseAutoplayVolume(C callback);

}
