== SonosControl ==

=== TODO ===

* convert from String to the StateVariable types which actually send XML sniplets

=== About ===
A Java API and a simple command line client for controlling the SONOS.

=== Usage ===

  $ buildr package
  $
  $ # Example usage:
  $ java -jar sonos-control-cli/target/sonos-control-cli-0.0.1.jar  start Esszimmer

=== Goals ===

==== Java "On" Button ====

To start with, I want to achieve a simple button which does the following:

* Connect all visible Sonos Devices, using the biggest current group or the first currently playing Sonos as the main device in the group
* If there is no currently playing device, still group all devices together, and start playing a preset station (first step: hardcode ndr2) 

=== Android "On" Button ===

Ideally, create an android app which only does the above
If possible, act like the "On" button on start, show a short success (or dont) - and quit.


=== Hardware "On" Button ===

Implement the above with Arduino or similar

=== Development ====
The actual Java API is partly generated, it is my goal to generate sonos-control-api and sonos-control-api-clingimpl from sonos-control-api-generator
The reason is, that the Sonos API contains many calls and types, and I think that generating it will lead to a complete Java API a lot faster.

