// AUTOGENERATED: f3db1e89503e65987b0faa4926a2512b
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.renderingcontrol;

import java.io.Serializable;
import com.google.common.base.Objects;
import com.google.common.base.Function;
import com.google.common.base.Preconditions;

public final class ChannelMap implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final Function<ChannelMap, String> GET_VALUE = new Function<ChannelMap, String>() {
        @Override
        public String apply(ChannelMap input) {
            return input == null ? null : input.getValue();
        }
    };


    private final String _value;

    private ChannelMap(String value) {
        _value = Preconditions.checkNotNull(value);
    } 

    public String getValue() {
        return _value;
    }

    public String toString() {
        return Objects.toStringHelper(this).add("value", _value).toString();
    }

    public int hashCode() {
        return Objects.hashCode(_value);
    }

    public boolean equals(Object other) {
        if (other instanceof ChannelMap) {
            ChannelMap obj = (ChannelMap)other;
            return Objects.equal(_value, obj._value);
        }
        return false;
    }

    public static ChannelMap getInstance(String value) {
        if (value != null && "NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        
        return value == null ? null : new ChannelMap(value);
    }
}
