// AUTOGENERATED: 9b109c4547db96d5fd25f592bac4dc75
// AUTOGENERATED: 09.01.2012 13:05:47
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.renderingcontrol;

public enum Channel {
    MASTER("Master"),
    LF("LF"),
    RF("RF");

    private final String _value;

    Channel(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static Channel getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (Channel v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}