// AUTOGENERATED: d6a763498ca91fc81e85ec5d705ed4f6
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.renderingcontrol;

public enum RampType {
    SLEEP_TIMER_RAMP_TYPE("SLEEP_TIMER_RAMP_TYPE"),
    ALARM_RAMP_TYPE("ALARM_RAMP_TYPE"),
    AUTOPLAY_RAMP_TYPE("AUTOPLAY_RAMP_TYPE");

    private final String _value;

    RampType(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static RampType getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (RampType v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}