// AUTOGENERATED: 75b34c5589a9112c1a5f1e35da06372b
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.contentdirectory;

public enum BrowseFlag {
    BROWSE_METADATA("BrowseMetadata"),
    BROWSE_DIRECT_CHILDREN("BrowseDirectChildren");

    private final String _value;

    BrowseFlag(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static BrowseFlag getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (BrowseFlag v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}