// AUTOGENERATED: 5755e7aebef620a44165d1d80f8b0a97
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.contentdirectory;

import com.google.common.base.Objects;
import java.io.Serializable;


public final class BrowseResult implements Serializable {
    private static final long serialVersionUID = 1L;

    private final Result _result;
    private final Count _numberReturned;
    private final Count _totalMatches;
    private final UpdateID _updateID;

    private BrowseResult(
        final Result result,
        final Count numberReturned,
        final Count totalMatches,
        final UpdateID updateID
    ) {
        _result = result;
        _numberReturned = numberReturned;
        _totalMatches = totalMatches;
        _updateID = updateID;
    } 

    public static BrowseResult getInstance(
        final Result result,
        final Count numberReturned,
        final Count totalMatches,
        final UpdateID updateID
    ) {
        return new BrowseResult(result, numberReturned, totalMatches, updateID);
    } 
    public Result getResult() {
        return _result;
    }
    public Count getNumberReturned() {
        return _numberReturned;
    }
    public Count getTotalMatches() {
        return _totalMatches;
    }
    public UpdateID getUpdateID() {
        return _updateID;
    }

    public String toString() {
        return Objects.toStringHelper(this)
        .add("result", _result)
        .add("numberReturned", _numberReturned)
        .add("totalMatches", _totalMatches)
        .add("updateID", _updateID)
        .toString();
    }

    public int hashCode() {
        return Objects.hashCode(
            _result,
            _numberReturned,
            _totalMatches,
            _updateID
        );
    }

    public boolean equals(Object other) {
        if (other instanceof BrowseResult) {
            BrowseResult obj = (BrowseResult)other;
            return 
                    Objects.equal(_result, obj._result) &&
                    Objects.equal(_numberReturned, obj._numberReturned) &&
                    Objects.equal(_totalMatches, obj._totalMatches) &&
                    Objects.equal(_updateID, obj._updateID) 
            ;
        }
        return false;
    }

}
