// AUTOGENERATED: c34039a498118414ebb4067347e66ce3
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.contentdirectory;

public enum ShareListRefreshState {
    NOTRUN("NOTRUN"),
    RUNNING("RUNNING"),
    DONE("DONE");

    private final String _value;

    ShareListRefreshState(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static ShareListRefreshState getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (ShareListRefreshState v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}