// AUTOGENERATED: 9d7917c5dd92ae2838d3befc6c9bf105
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.clingimpl.services;

import de.kalass.sonoscontrol.api.services.SystemPropertiesService;
import de.kalass.sonoscontrol.api.core.EventListener;

import org.fourthline.cling.model.gena.GENASubscription;
import org.fourthline.cling.model.action.ActionArgumentValue;
import org.fourthline.cling.UpnpService;
import org.fourthline.cling.model.action.ActionInvocation;
import org.fourthline.cling.model.meta.Device;
import org.fourthline.cling.model.types.InvalidValueException;
import org.fourthline.cling.model.types.UnsignedIntegerFourBytes;
import org.fourthline.cling.model.state.StateVariableValue;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;

import com.google.common.base.Objects;

import de.kalass.sonoscontrol.api.core.ErrorStrategy;

import de.kalass.sonoscontrol.clingimpl.services.AbstractServiceImpl;

import de.kalass.sonoscontrol.api.core.Callback0;
import de.kalass.sonoscontrol.api.core.Callback1;
import de.kalass.sonoscontrol.api.model.systemproperties.VariableStringValue;
import de.kalass.sonoscontrol.api.model.systemproperties.IsExpired;
import de.kalass.sonoscontrol.api.model.systemproperties.AccountID;
import de.kalass.sonoscontrol.api.model.systemproperties.VariableName;
import de.kalass.sonoscontrol.api.model.systemproperties.AccountMd;
import de.kalass.sonoscontrol.api.model.systemproperties.AccountType;
import de.kalass.sonoscontrol.api.model.systemproperties.StubsCreated;
import de.kalass.sonoscontrol.api.model.systemproperties.AccountPassword;

@SuppressWarnings("rawtypes")
public final class SystemPropertiesServiceClingImpl extends AbstractServiceImpl implements SystemPropertiesService {
    private static final org.slf4j.Logger LOG = org.slf4j.LoggerFactory.getLogger(SystemPropertiesServiceClingImpl.class);
    

    public SystemPropertiesServiceClingImpl(UpnpService upnpService, Device device, ErrorStrategy errorStrategy) {
        super("SystemProperties", upnpService, device, errorStrategy);
    }


    public <C extends Callback0> C setString(final VariableName variableName, final VariableStringValue stringValue, final C successHandler) {
        return execute(successHandler, new Call<C>("SetString") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"string", "VariableName", variableName == null ? null : variableName.getValue());
                setInput(invocation,"string", "StringValue", stringValue == null ? null : stringValue.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback1<VariableStringValue>> C retrieveString(final VariableName variableName, final C successHandler) {
        return execute(successHandler, new Call<C>("GetString") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"string", "VariableName", variableName == null ? null : variableName.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                 assert invocation.getOutput().length == 1;
                 final ActionArgumentValue[] output = invocation.getOutput();
                 final VariableStringValue value = VariableStringValue.getInstance((String)getValue("string",output[0].getValue()));
                 handler.success(value);
            }
        });
    }

    public <C extends Callback0> C remove(final VariableName variableName, final C successHandler) {
        return execute(successHandler, new Call<C>("Remove") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"string", "VariableName", variableName == null ? null : variableName.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback1<VariableStringValue>> C retrieveWebCode(final AccountType accountType, final C successHandler) {
        return execute(successHandler, new Call<C>("GetWebCode") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                 assert invocation.getOutput().length == 1;
                 final ActionArgumentValue[] output = invocation.getOutput();
                 final VariableStringValue value = VariableStringValue.getInstance((String)getValue("string",output[0].getValue()));
                 handler.success(value);
            }
        });
    }

    public <C extends Callback0> C provisionTrialAccount(final AccountType accountType, final C successHandler) {
        return execute(successHandler, new Call<C>("ProvisionTrialAccount") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback1<IsExpired>> C provisionCredentialedTrialAccount(final AccountType accountType, final AccountID accountID, final AccountPassword accountPassword, final C successHandler) {
        return execute(successHandler, new Call<C>("ProvisionCredentialedTrialAccount") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
                setInput(invocation,"string", "AccountID", accountID == null ? null : accountID.getValue());
                setInput(invocation,"string", "AccountPassword", accountPassword == null ? null : accountPassword.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                 assert invocation.getOutput().length == 1;
                 final ActionArgumentValue[] output = invocation.getOutput();
                 final IsExpired value = IsExpired.getInstance((Boolean)getValue("boolean",output[0].getValue()));
                 handler.success(value);
            }
        });
    }

    public <C extends Callback0> C migrateTrialAccount(final AccountType targetAccountType, final AccountID targetAccountID, final AccountPassword targetAccountPassword, final C successHandler) {
        return execute(successHandler, new Call<C>("MigrateTrialAccount") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "TargetAccountType", targetAccountType == null ? null : targetAccountType.getValue());
                setInput(invocation,"string", "TargetAccountID", targetAccountID == null ? null : targetAccountID.getValue());
                setInput(invocation,"string", "TargetAccountPassword", targetAccountPassword == null ? null : targetAccountPassword.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback0> C addAccount(final AccountType accountType, final AccountID accountID, final AccountPassword accountPassword, final C successHandler) {
        return execute(successHandler, new Call<C>("AddAccount") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
                setInput(invocation,"string", "AccountID", accountID == null ? null : accountID.getValue());
                setInput(invocation,"string", "AccountPassword", accountPassword == null ? null : accountPassword.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback0> C removeAccount(final AccountType accountType, final AccountID accountID, final C successHandler) {
        return execute(successHandler, new Call<C>("RemoveAccount") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
                setInput(invocation,"string", "AccountID", accountID == null ? null : accountID.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback0> C editAccountPassword(final AccountType accountType, final AccountID accountID, final AccountPassword newAccountPassword, final C successHandler) {
        return execute(successHandler, new Call<C>("EditAccountPassword") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
                setInput(invocation,"string", "AccountID", accountID == null ? null : accountID.getValue());
                setInput(invocation,"string", "NewAccountPassword", newAccountPassword == null ? null : newAccountPassword.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback0> C editAccountMd(final AccountType accountType, final AccountID accountID, final AccountMd newAccountMd, final C successHandler) {
        return execute(successHandler, new Call<C>("EditAccountMd") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
                setInput(invocation,"ui4", "AccountType", accountType == null ? null : accountType.getValue());
                setInput(invocation,"string", "AccountID", accountID == null ? null : accountID.getValue());
                setInput(invocation,"string", "NewAccountMd", newAccountMd == null ? null : newAccountMd.getValue());
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback0> C doPostUpdateTasks(final C successHandler) {
        return execute(successHandler, new Call<C>("DoPostUpdateTasks") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    public <C extends Callback0> C resetThirdPartyCredentials(final C successHandler) {
        return execute(successHandler, new Call<C>("ResetThirdPartyCredentials") {
            @Override
            public void prepareArguments(ActionInvocation invocation)
                    throws InvalidValueException {
                // Throws InvalidValueException if the value is of wrong type
            }
            @Override
            public void success(C handler, ActionInvocation invocation) {
                // no return values
                handler.success();
            }
        });
    }

    protected void eventReceived(GENASubscription subscription) {
        final Map values = subscription.getCurrentValues();
        final Map<String, Object> stored = getStoredValues();


        setEventedValues(stored);
        
        // after the values were updated, send the change notifications
    }

    
    
    
    
    
    
    
    
}
