// AUTOGENERATED: 1e13011bc455d7d890b257d50a0b7d80
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.alarmclock;

import com.google.common.base.Objects;
import java.io.Serializable;


public final class GetTimeZoneAndRuleResult implements Serializable {
    private static final long serialVersionUID = 1L;

    private final TimeZoneIndex _index;
    private final TimeZoneAutoAdjustDst _autoAdjustDst;
    private final TimeZone _currentTimeZone;

    private GetTimeZoneAndRuleResult(
        final TimeZoneIndex index,
        final TimeZoneAutoAdjustDst autoAdjustDst,
        final TimeZone currentTimeZone
    ) {
        _index = index;
        _autoAdjustDst = autoAdjustDst;
        _currentTimeZone = currentTimeZone;
    } 

    public static GetTimeZoneAndRuleResult getInstance(
        final TimeZoneIndex index,
        final TimeZoneAutoAdjustDst autoAdjustDst,
        final TimeZone currentTimeZone
    ) {
        return new GetTimeZoneAndRuleResult(index, autoAdjustDst, currentTimeZone);
    } 
    public TimeZoneIndex getIndex() {
        return _index;
    }
    public TimeZoneAutoAdjustDst getAutoAdjustDst() {
        return _autoAdjustDst;
    }
    public TimeZone getCurrentTimeZone() {
        return _currentTimeZone;
    }

    public String toString() {
        return Objects.toStringHelper(this)
        .add("index", _index)
        .add("autoAdjustDst", _autoAdjustDst)
        .add("currentTimeZone", _currentTimeZone)
        .toString();
    }

    public int hashCode() {
        return Objects.hashCode(
            _index,
            _autoAdjustDst,
            _currentTimeZone
        );
    }

    public boolean equals(Object other) {
        if (other instanceof GetTimeZoneAndRuleResult) {
            GetTimeZoneAndRuleResult obj = (GetTimeZoneAndRuleResult)other;
            return 
                    Objects.equal(_index, obj._index) &&
                    Objects.equal(_autoAdjustDst, obj._autoAdjustDst) &&
                    Objects.equal(_currentTimeZone, obj._currentTimeZone) 
            ;
        }
        return false;
    }

}
