// AUTOGENERATED: 2c8a0ba6257f126279057b3211093cbc
// AUTOGENERATED: 09.01.2012 13:05:47
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.alarmclock;

import com.google.common.base.Objects;
import java.io.Serializable;


public final class ListAlarmsResult implements Serializable {
    private static final long serialVersionUID = 1L;

    private final AlarmList _currentAlarmList;
    private final AlarmListVersion _currentAlarmListVersion;

    private ListAlarmsResult(
        final AlarmList currentAlarmList,
        final AlarmListVersion currentAlarmListVersion
    ) {
        _currentAlarmList = currentAlarmList;
        _currentAlarmListVersion = currentAlarmListVersion;
    } 

    public static ListAlarmsResult getInstance(
        final AlarmList currentAlarmList,
        final AlarmListVersion currentAlarmListVersion
    ) {
        return new ListAlarmsResult(currentAlarmList, currentAlarmListVersion);
    } 
    public AlarmList getCurrentAlarmList() {
        return _currentAlarmList;
    }
    public AlarmListVersion getCurrentAlarmListVersion() {
        return _currentAlarmListVersion;
    }

    public String toString() {
        return Objects.toStringHelper(this)
        .add("currentAlarmList", _currentAlarmList)
        .add("currentAlarmListVersion", _currentAlarmListVersion)
        .toString();
    }

    public int hashCode() {
        return Objects.hashCode(
            _currentAlarmList,
            _currentAlarmListVersion
        );
    }

    public boolean equals(Object other) {
        if (other instanceof ListAlarmsResult) {
            ListAlarmsResult obj = (ListAlarmsResult)other;
            return 
                    Objects.equal(_currentAlarmList, obj._currentAlarmList) &&
                    Objects.equal(_currentAlarmListVersion, obj._currentAlarmListVersion) 
            ;
        }
        return false;
    }

}
