// AUTOGENERATED: 85241d808935d720c9f452b2ec2827a2
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.alarmclock;

public enum Recurrence {
    ONCE("ONCE"),
    WEEKDAYS("WEEKDAYS"),
    WEEKENDS("WEEKENDS"),
    DAILY("DAILY");

    private final String _value;

    Recurrence(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static Recurrence getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (Recurrence v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}