// AUTOGENERATED: 4e8acd94d4c923484378d0b4a79648ef
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.alarmclock;

import java.io.Serializable;
import com.google.common.base.Objects;
import com.google.common.base.Function;
import com.google.common.base.Preconditions;

public final class TimeFormat implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final Function<TimeFormat, String> GET_VALUE = new Function<TimeFormat, String>() {
        @Override
        public String apply(TimeFormat input) {
            return input == null ? null : input.getValue();
        }
    };


    private final String _value;

    private TimeFormat(String value) {
        _value = Preconditions.checkNotNull(value);
    } 

    public String getValue() {
        return _value;
    }

    public String toString() {
        return Objects.toStringHelper(this).add("value", _value).toString();
    }

    public int hashCode() {
        return Objects.hashCode(_value);
    }

    public boolean equals(Object other) {
        if (other instanceof TimeFormat) {
            TimeFormat obj = (TimeFormat)other;
            return Objects.equal(_value, obj._value);
        }
        return false;
    }

    public static TimeFormat getInstance(String value) {
        if (value != null && "NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        
        return value == null ? null : new TimeFormat(value);
    }
}
