// AUTOGENERATED: df61ff4f9c991dbe069fb2e5df873842
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.zonegrouptopology;

public enum UnresponsiveDeviceActionType {
    REMOVE("Remove"),
    VERIFY_THEN_REMOVE_SYSTEMWIDE("VerifyThenRemoveSystemwide");

    private final String _value;

    UnresponsiveDeviceActionType(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static UnresponsiveDeviceActionType getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (UnresponsiveDeviceActionType v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}