// AUTOGENERATED: 5d4e827019fb9f2f29a4c1f2fdbb87c6
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.zonegrouptopology;

public enum UpdateType {
    ALL("All"),
    SOFTWARE("Software");

    private final String _value;

    UpdateType(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static UpdateType getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (UpdateType v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}