// AUTOGENERATED: fe02a05a2aa96f40259ee8db7fdae60a
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.avtransport;

import java.io.Serializable;
import com.google.common.base.Objects;
import com.google.common.base.Function;
import com.google.common.base.Preconditions;

public final class AVTransportURI implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final Function<AVTransportURI, String> GET_VALUE = new Function<AVTransportURI, String>() {
        @Override
        public String apply(AVTransportURI input) {
            return input == null ? null : input.getValue();
        }
    };


    private final String _value;

    private AVTransportURI(String value) {
        _value = Preconditions.checkNotNull(value);
    } 

    public String getValue() {
        return _value;
    }

    public String toString() {
        return Objects.toStringHelper(this).add("value", _value).toString();
    }

    public int hashCode() {
        return Objects.hashCode(_value);
    }

    public boolean equals(Object other) {
        if (other instanceof AVTransportURI) {
            AVTransportURI obj = (AVTransportURI)other;
            return Objects.equal(_value, obj._value);
        }
        return false;
    }

    public static AVTransportURI getInstance(String value) {
        if (value != null && "NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        
        return value == null ? null : new AVTransportURI(value);
    }
}
