// AUTOGENERATED: 3d7e90783d823f7c8173692c9faa40fe
// AUTOGENERATED: 09.01.2012 13:05:47
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.avtransport;

import com.google.common.base.Objects;
import java.io.Serializable;


public final class GetTransportInfoResult implements Serializable {
    private static final long serialVersionUID = 1L;

    private final TransportState _currentTransportState;
    private final TransportStatus _currentTransportStatus;
    private final TransportPlaySpeed _currentSpeed;

    private GetTransportInfoResult(
        final TransportState currentTransportState,
        final TransportStatus currentTransportStatus,
        final TransportPlaySpeed currentSpeed
    ) {
        _currentTransportState = currentTransportState;
        _currentTransportStatus = currentTransportStatus;
        _currentSpeed = currentSpeed;
    } 

    public static GetTransportInfoResult getInstance(
        final TransportState currentTransportState,
        final TransportStatus currentTransportStatus,
        final TransportPlaySpeed currentSpeed
    ) {
        return new GetTransportInfoResult(currentTransportState, currentTransportStatus, currentSpeed);
    } 
    public TransportState getCurrentTransportState() {
        return _currentTransportState;
    }
    public TransportStatus getCurrentTransportStatus() {
        return _currentTransportStatus;
    }
    public TransportPlaySpeed getCurrentSpeed() {
        return _currentSpeed;
    }

    public String toString() {
        return Objects.toStringHelper(this)
        .add("currentTransportState", _currentTransportState)
        .add("currentTransportStatus", _currentTransportStatus)
        .add("currentSpeed", _currentSpeed)
        .toString();
    }

    public int hashCode() {
        return Objects.hashCode(
            _currentTransportState,
            _currentTransportStatus,
            _currentSpeed
        );
    }

    public boolean equals(Object other) {
        if (other instanceof GetTransportInfoResult) {
            GetTransportInfoResult obj = (GetTransportInfoResult)other;
            return 
                    Objects.equal(_currentTransportState, obj._currentTransportState) &&
                    Objects.equal(_currentTransportStatus, obj._currentTransportStatus) &&
                    Objects.equal(_currentSpeed, obj._currentSpeed) 
            ;
        }
        return false;
    }

}
