// AUTOGENERATED: 119e5072a9c24b9ac61b9c2cc595e463
// AUTOGENERATED: 09.01.2012 13:05:47
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.avtransport;

import java.io.Serializable;
import com.google.common.base.Objects;
import com.google.common.base.Preconditions;

public final class ISO8601Time implements Serializable {
    private static final long serialVersionUID = 1L;


    private final String _value;

    private ISO8601Time(String value) {
        _value = Preconditions.checkNotNull(value);
    } 

    public String getValue() {
        return _value;
    }

    public String toString() {
        return Objects.toStringHelper(this).add("value", _value).toString();
    }

    public int hashCode() {
        return Objects.hashCode(_value);
    }

    public boolean equals(Object other) {
        if (other instanceof ISO8601Time) {
            ISO8601Time obj = (ISO8601Time)other;
            return Objects.equal(_value, obj._value);
        }
        return false;
    }

    public static ISO8601Time getInstance(String value) {
        if (value != null && "NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        
        return value == null ? null : new ISO8601Time(value);
    }
}
