// AUTOGENERATED: 9abddc3823fa2f4482fd57f00cb1a470
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.avtransport;

public enum RecordStorageMedium {
    NONE("NONE");

    public static final RecordStorageMedium DEFAULT_VALUE = NONE;
    private final String _value;

    RecordStorageMedium(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static RecordStorageMedium getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (RecordStorageMedium v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}