// AUTOGENERATED: 070b31ad0e9f505f0a0867f4cedef16a
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.avtransport;

public enum SeekMode {
    TRACK_NR("TRACK_NR"),
    REL_TIME("REL_TIME"),
    SECTION("SECTION");

    private final String _value;

    SeekMode(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static SeekMode getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (SeekMode v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}