// AUTOGENERATED: 8f1d83041b3f4bd9f8874ac66e947e7e
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.avtransport;

public enum TransportPlaySpeed {
    ONE("1");

    public static final TransportPlaySpeed DEFAULT_VALUE = ONE;
    private final String _value;

    TransportPlaySpeed(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static TransportPlaySpeed getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (TransportPlaySpeed v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}