// AUTOGENERATED: 48f71cfc4308ba6a7835c24ae22ba65e
// AUTOGENERATED: 09.01.2012 12:49:21
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.deviceproperties;

public enum LEDState {
    ON("On"),
    OFF("Off");

    private final String _value;

    LEDState(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static LEDState getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (LEDState v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}