// AUTOGENERATED: 7b733d3e3f9bffa9111e1d0843084e6a
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.connectionmanager;

public enum Direction {
    INPUT("Input"),
    OUTPUT("Output");

    private final String _value;

    Direction(String value) {
        _value = value;
    } 

    public String getValue() {
        return _value;
    }

    public static Direction getInstance(String value) {
        if ("NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        for (Direction v: values()) {
            if (v._value.equals(value)) {
                return v;
            }
        }
        throw new IllegalArgumentException("Could not find " + value);   
    }

}