// AUTOGENERATED: fb77e3bc7f433b6aef56cec0c57343d1
// AUTOGENERATED: Please feel free to enhance this sourcecode manually 
// AUTOGENERATED: (for example by adding more structure or convenience methods), and
// AUTOGENERATED: do not forget to remove this comment, especially the very first line so your changes are not overridden
package de.kalass.sonoscontrol.api.model.connectionmanager;

import java.io.Serializable;
import com.google.common.base.Objects;
import com.google.common.base.Function;
import com.google.common.base.Preconditions;

public final class ProtocolInfo implements Serializable {
    private static final long serialVersionUID = 1L;

    public static final Function<ProtocolInfo, String> GET_VALUE = new Function<ProtocolInfo, String>() {
        @Override
        public String apply(ProtocolInfo input) {
            return input == null ? null : input.getValue();
        }
    };


    private final String _value;

    private ProtocolInfo(String value) {
        _value = Preconditions.checkNotNull(value);
    } 

    public String getValue() {
        return _value;
    }

    public String toString() {
        return Objects.toStringHelper(this).add("value", _value).toString();
    }

    public int hashCode() {
        return Objects.hashCode(_value);
    }

    public boolean equals(Object other) {
        if (other instanceof ProtocolInfo) {
            ProtocolInfo obj = (ProtocolInfo)other;
            return Objects.equal(_value, obj._value);
        }
        return false;
    }

    public static ProtocolInfo getInstance(String value) {
        if (value != null && "NOT_IMPLEMENTED".equals(value)) {
            return null;
        }
        
        return value == null ? null : new ProtocolInfo(value);
    }
}
